// src/config.ts – Static configuration for MobileVideoController

export const MVC_CONFIG = {
    MIN_VIDEO_AREA: 150 * 150,
    MIN_VIDEO_HEIGHT: 50,
    EDGE: 10,
    INTERACTION_TIMEOUT: 4500,
    VISIBILITY_GUARDIAN_DELAY: 500,
    UI_FADE_TIMEOUT: 3500,
    UI_FADE_OPACITY: 0,
    LONG_PRESS_DURATION_MS: 600,
    SLIDER_SENSITIVITY: 0.003,
    SLIDER_POWER: 1.2,
    LONG_PRESS_VIBRATE_MS: 15,
    INITIAL_EVAL_DELAY: 500,
    BACKDROP_POINTER_EVENTS_DELAY: 150,
    // ECO SETTINGS
    MUTATION_DEBOUNCE_MS: 800,
    SCROLL_END_TIMEOUT: 150,
    STORAGE_DEBOUNCE_MS: 2000,
    // GESTURE SETTINGS
    GESTURE_MOVE_THRESHOLD: 10,
    LONG_PRESS_MOVE_TOLERANCE: 24,
    GESTURE_SEEK_SENSITIVITY: 0.1,
    GESTURE_LONG_PRESS_DELAY: 600,
    GESTURE_SPEED_BOOST: 2.0,
    DOUBLE_TAP_DELAY: 300,
    DOUBLE_TAP_MAX_DISTANCE: 40,
    DOUBLE_TAP_RESET_DELAY: 650,
    CLICK_DELAY: 250,
    // STEPPER SETTINGS
    SPEED_TAP_STEP: 0.10,
    SPEED_HOLD_STEP: 0.05,
    SPEED_HOLD_INITIAL_DELAY_MS: 400,
    SPEED_HOLD_INTERVAL_MS: 120,
    // SNAP POINTS FOR PINCH ZOOM
    PINCH_SNAP_POINTS: [0.5, 1.0, 1.25, 1.5, 2.0, 3.0],
    PINCH_SNAP_THRESHOLD: 0.15
};

