// src/config.ts – Central configuration for GlideVideo (MobileVideoController)

export const MVC_CONFIG = {
	// LAYOUT & DIMENSIONS
	MIN_VIDEO_AREA: 150 * 150,
	MIN_VIDEO_HEIGHT: 50,
	EDGE: 10,
	EDGE_TOUCH_PROTECTION_PADDING: 18,
	SIDEBAR_MIN_HEIGHT: 120,
	SIDEBAR_MAX_HEIGHT: 220,
	SIDEBAR_HEIGHT_RATIO: 0.55,

	// TIMEOUTS & DELAYS
	INTERACTION_TIMEOUT: 4500,
	VISIBILITY_GUARDIAN_DELAY: 500,
	HIDE_GRACE_PERIOD_MS: 250,
	UI_FADE_TIMEOUT: 3500,
	UI_FADE_ANIMATION_DURATION: 350,
	TOAST_FADE_DELAY: 1500,
	DOUBLE_TAP_UI_HIDE_DELAY: 800,
	SLIDER_UI_HIDE_DELAY: 1200,
	CONTROLS_COLLAPSE_DELAY: 4000,
	LONG_PRESS_DURATION_MS: 600,
	LONG_PRESS_VIBRATE_MS: 15,
	INITIAL_EVAL_DELAY: 500,
	HAPTIC_VIBRATION_MS: 10,

	// VIDEO SELECTION
	LINKED_VIDEO_MIN_WIDTH: 250,
	LINKED_VIDEO_MIN_HEIGHT: 140,
	SMALL_MUTED_VIDEO_HEIGHT: 150,

	// ECO & STORAGE SETTINGS
	MUTATION_DEBOUNCE_MS: 250,
	MUTATION_DEBOUNCE_MAX_MS: 1000,
	SCROLL_END_TIMEOUT: 150,
	STORAGE_DEBOUNCE_MS: 2000,
	POSITION_SAVE_INTERVAL_MS: 2000,
	MAX_POSITION_HISTORY: 100,
	POSITION_SAVE_MIN_TIME: 3,
	POSITION_SAVE_END_BUFFER: 5,

	// GESTURE SETTINGS
	GESTURE_MOVE_THRESHOLD: 10,
	LONG_PRESS_MOVE_TOLERANCE: 24,
	GESTURE_SEEK_SENSITIVITY: 0.15,
	GESTURE_VERTICAL_SENSITIVITY: 1.1,
	GESTURE_SEEK_DEADZONE: 5.0,
	GESTURE_SPEED_BOOST: 2.0,
	DOUBLE_TAP_DELAY: 300,
	DOUBLE_TAP_MAX_DISTANCE: 40,
	DOUBLE_TAP_RESET_DELAY: 650,
	DOUBLE_TAP_LOCK_RELEASE_MS: 250,
	CLICK_DELAY: 250,

	// SPEED CONTROL SETTINGS
	SPEED_MIN: 0.1,
	SPEED_MAX: 16.0,
	SPEED_DEFAULT: 1.0,
	SPEED_TAP_STEP: 0.1,
	SPEED_HOLD_STEP: 0.05,
	SPEED_HOLD_INITIAL_DELAY_MS: 400,
	SPEED_HOLD_INTERVAL_MS: 120,
	SPEED_STEPPER_STEP: 0.05,

	// MINIMAL SPEED FAB SETTINGS
	FAB_SPEED_MIN: 0.5,
	FAB_SPEED_MAX: 2.0,
	FAB_SPEED_STEP: 0.1,

	// SKIP DURATION SETTINGS
	SKIP_DEFAULT: 10,
	SKIP_MIN: 5,
	SKIP_MAX: 300,
	SKIP_STEPPER_STEP: 5,

	// SNAP POINTS FOR PINCH ZOOM
	PINCH_SNAP_POINTS: [0.5, 1.0, 1.25, 1.5, 2.0, 3.0],
	PINCH_SNAP_THRESHOLD: 0.15,
};
