import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig({
  plugins: [
    monkey({
      entry: 'src/main.ts',
      userscript: {
        name: 'StreamGrabber',
        namespace: 'https://github.com/streamgrabber-lite',
        version: '2.4.0',
        description: 'Lightweight HLS/Video downloader. Pause/Resume. AES-128. fMP4. Mobile + Desktop.',
        author: 'StreamGrabber',
        license: 'MIT',
        match: ['*://*/*'],
        exclude: [
          // Global & Infrastructure Exclusions
          '*://*.gov/*',
          '*://*.gov.*/*',
          '*://*.mil/*',
          '*://*.mil.*/*',
          '*://*.int/*',
          '*://*.edu/*',
          '*://*.edu.*/*',
          '*://*.ac.*/*',
          '*://*.nic.in/*',
          '*://localhost/*',
          '*://127.0.0.1/*',
          '*://[::1]/*',
          '*://10.*.*.*/*',
          '*://192.168.*.*/*',
          '*://172.1[6-9].*/*', // Covers part of private range
          '*://172.2[0-9].*/*', // Covers part of private range
          '*://172.3[0-1].*/*', // Covers part of private range
          // Search & Portals
          '*://*.google.*/*',
          '*://*.bing.com/*',
          '*://*.duckduckgo.com/*',
          '*://*.baidu.com/*',
          '*://*.yahoo.com/*',
          '*://*.yandex.*/*',
          // Social Media
          '*://*.facebook.com/*',
          '*://*.instagram.com/*',
          '*://*.x.com/*',
          '*://*.twitter.com/*',
          '*://*.linkedin.com/*',
          '*://*.tiktok.com/*',
          '*://*.reddit.com/*',
          '*://*.redd.it/*',
          '*://*.pinterest.com/*',
          '*://*.snapchat.com/*',
          '*://*.tumblr.com/*',
          '*://*.threads.net/*',
          '*://*.bluesky.social/*',
          '*://*.mastodon.social/*',
          // Video & Music (Official)
          '*://*.youtube.*/*',
          '*://*.twitch.tv/*',
          '*://*.netflix.com/*',
          '*://*.disneyplus.com/*',
          '*://*.hulu.com/*',
          '*://*.hbomax.com/*',
          '*://*.max.com/*',
          '*://*.paramountplus.com/*',
          '*://*.peacocktv.com/*',
          '*://*.primevideo.com/*',
          '*://*.spotify.com/*',
          '*://*.soundcloud.com/*',
          '*://*.deezer.com/*',
          '*://*.tidal.com/*',
          // Communication
          '*://*.whatsapp.*/*',
          '*://*.telegram.*/*',
          '*://*.discord.*/*',
          '*://*.skype.com/*',
          // Banking & Finance
          '*://*.chase.com/*',
          '*://*.bankofamerica.com/*',
          '*://*.wellsfargo.com/*',
          '*://*.citibank.com/*',
          '*://*.capitalone.com/*',
          '*://*.americanexpress.com/*',
          '*://*.paypal.com/*',
          '*://*.stripe.com/*',
          '*://*.venmo.com/*',
          '*://*.coinbase.com/*',
          '*://*.binance.com/*',
          '*://*.fidelity.com/*',
          '*://*.vanguard.com/*',
          '*://*.schwab.com/*',
          '*://*.robinhood.com/*',
          // Shopping & E-commerce
          '*://*.amazon.*/*',
          '*://*.ebay.com/*',
          '*://*.target.com/*',
          '*://*.walmart.com/*',
          '*://*.bestbuy.com/*',
          '*://*.etsy.com/*',
          '*://*.aliexpress.com/*',
          '*://*.alibaba.com/*',
          '*://*.shopify.com/*',
          // News & Media
          '*://*.nytimes.com/*',
          '*://*.cnn.com/*',
          '*://*.bbc.*/*',
          '*://*.reuters.com/*',
          '*://*.theguardian.*/*',
          '*://*.forbes.com/*',
          '*://*.bloomberg.com/*',
          '*://*.wsj.com/*',
          // Knowledge & Education
          '*://*.wikipedia.*/*',
          '*://*.wikimedia.*/*',
          '*://*.coursera.org/*',
          '*://*.udemy.com/*',
          '*://*.khanacademy.org/*',
          '*://*.duolingo.com/*',
          '*://*.quora.com/*',
          // Developer Tools & Work
          '*://*.github.*/*',
          '*://*.gitlab.*/*',
          '*://*.stackoverflow.com/*',
          '*://*.npmjs.com/*',
          '*://*.docker.com/*',
          '*://*.git-scm.com/*',
          '*://*.atlassian.*/*',
          '*://*.jira.com/*',
          // Productivity & Enterprise
          '*://*.slack.com/*',
          '*://*.zoom.*/*',
          '*://*.microsoft.com/*',
          '*://*.office.com/*',
          '*://*.outlook.com/*',
          '*://*.live.com/*',
          '*://*.notion.so/*',
          '*://*.trello.com/*',
          '*://*.asana.com/*',
          '*://*.monday.com/*',
          // Cloud Storage
          '*://*.dropbox.com/*',
          '*://*.box.com/*',
          '*://*.wetransfer.com/*',
          '*://*.mega.nz/*',
          '*://*.icloud.com/*',
          // Tools & Utilities
          '*://*.speedtest.net/*',
          '*://*.canva.com/*',
          '*://*.adobe.com/*',
          '*://*.figma.com/*',
          // Security & Identity
          '*://*.lastpass.com/*',
          '*://*.1password.com/*',
          '*://*.bitwarden.com/*',
          '*://*.dashlane.com/*',
          '*://*.okta.com/*',
          // AI Tools
          '*://*.chatgpt.com/*',
          '*://*.openai.com/*',
          '*://*.claude.ai/*',
          '*://*.anthropic.com/*',
          '*://*.perplexity.ai/*',
        ],
        'run-at': 'document-start',
        grant: [
          'GM_xmlhttpRequest',
          'GM_addStyle',
          'GM_getValue',
          'GM_setValue',
          'GM_download',
          'GM_notification',
          'GM_registerMenuCommand',
          'unsafeWindow',
        ],
        connect: ['*'],
      },
      build: {
        fileName: 'streamgrabber.user.js',
        externalGlobals: {},
      },
    }),
  ],
  build: {
    minify: 'esbuild',
    target: 'es2022',
  },
});